server:
  port: 80

#视图解析器
spring:
   mvc:
     view:
        prefix: /
        suffix: .html

#映射静态资源       （映射所有，static-locations下的所有东西都放过static-path-pattern: /**）
     static-path-pattern: /**
   resources:
     static-locations: classpath:/templates/,classpath:/META-NF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

#Thymeleaf配置
   thymeleaf:
     encoding: UTF-8
     #开发时关闭缓存,不然没法看到实时页面(要重启)
     cache: false
     prefix: classpath:/templates/ #(默认)
     suffix: .html		  #(默认)



eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka6001.com:6001/eureka/
  instance:
    instance-id: microservice-consumer-80
    prefer-ip-address: true     #访问路径可以显示IP地址

feign:
  hystrix:
    enabled: true

